export const data= [
    { name: "Alkaline phosphatase  4", isolated: "Chryseobacterium sp. GCEP-77", activity: "Fitasa" },
    { name: "Alkaline phosphatase PafA", isolated: "Chryseobacterium sp. GCEP-77", activity: "Fitasa" },
    { name: "Alkaline phosphatase D", isolated: "Chryseobacterium sp. GCEP-77", activity: "Fitasa" },
    { name: "Bifunctional oligoribonuclease and PAP phosphatase NrnA", isolated: "Chryseobacterium sp. GCEP-77", activity: "Fitasa" },
    { name: "Phosphoglycolate phosphatase", isolated: "Chryseobacterium sp. GCEP-77", activity: "Fitasa" },
    { name: "Hexitol phosphatase B", isolated: "Chryseobacterium sp. GCEP-77", activity: "Fitasa" },
    { name: "Pyrophosphatase PpaX", isolated: "Chryseobacterium sp. GCEP-77", activity: "Fitasa" },
    { name: "Sugar phosphatase YbiV", isolated: "Chryseobacterium sp. GCEP-77", activity: "Fitasa" },
    { name: "Serine/threonine-protein phosphatase  1", isolated: "Chryseobacterium sp. GCEP-77", activity: "Fitasa" },
    { name: "GDP-mannose pyrophosphatase NudK", isolated: "Chryseobacterium sp. GCEP-77", activity: "Fitasa" },
    { name: "Alkaline phosphatase synthesis transcriptional regulatory protein PhoP", isolated: "Chryseobacterium sp. GCEP-77", activity: "Fitasa" },
    { name: "Inorganic pyrophosphatase", isolated: "Chryseobacterium sp. GCEP-77", activity: "Fitasa" },
    { name: "Putative low molecular weight protein-tyrosine-phosphatase", isolated: "Chryseobacterium sp. GCEP-77", activity: "Fitasa" },
    { name: "Undecaprenyl-diphosphatase", isolated: "Chryseobacterium sp. GCEP-77", activity: "Fitasa" },
    { name: "Alkaline phosphatase", isolated: "Klebsiella pneumoniae GCEP-84", activity: "Fitasa" },
    { name: "Putative phosphatase", isolated: "Klebsiella pneumoniae GCEP-84", activity: "Fitasa" },
    { name: "HMP-PP phosphatase", isolated: "Klebsiella pneumoniae GCEP-84", activity: "Fitasa" },
    { name: "Class B acid phosphatase", isolated: "Klebsiella pneumoniae GCEP-84", activity: "Fitasa" },
    { name: "Phosphohistidine phosphatase SixA", isolated: "Klebsiella pneumoniae GCEP-84", activity: "Fitasa" },
    { name: "Inositol-1-monophosphatase", isolated: "Klebsiella pneumoniae GCEP-84", activity: "Fitasa" },
    { name: "Low molecular weight protein-tyrosine-phosphatase Etp", isolated: "Klebsiella pneumoniae GCEP-84", activity: "Fitasa" },
    { name: "Dihydroneopterin triphosphate diphosphatase", isolated: "Klebsiella pneumoniae GCEP-84", activity: "Fitasa" },
    { name: "Phosphatase NudJ", isolated: "Klebsiella pneumoniae GCEP-84", activity: "Fitasa" },
    { name: "Major phosphate-irrepressible acid phosphatase", isolated: "Klebsiella pneumoniae GCEP-84", activity: "Fitasa" },
    { name: "Alkaline phosphatase synthesis transcriptional regulatory protein PhoP", isolated: "Klebsiella pneumoniae GCEP-84", activity: "Fitasa" },
    { name: "Putative phosphatase YcdX", isolated: "Klebsiella pneumoniae GCEP-84", activity: "Fitasa" },
    { name: "Inorganic pyrophosphatase", isolated: "Klebsiella pneumoniae GCEP-84", activity: "Fitasa" },
    { name: "Inorganic pyrophosphatase", isolated: "Klebsiella pneumoniae GCEP-84", activity: "Fitasa" },
    { name: "Inorganic triphosphatase", isolated: "Klebsiella pneumoniae GCEP-84", activity: "Fitasa" },
];